=== JasminDreasond/NodeL2/data/Templates/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "NodeL2 Character Base Class Template",
    "type": "object",
    "properties": {
      "template": {
        "type": "object",
        "properties": {
          "baseId": {
            "type": "integer"
          },
          "classId": {
            "type": "integer"
          },
          "race": {
            "type": "integer"
          },
          "crafter": {
            "type": "boolean"
          }
        },
        "required": [
          "baseId",
          "classId",
          "race",
          "crafter"
        ]
      },
      "base": {
        "type": "object",
        "properties": {
          "str": {
            "type": "integer"
          },
          "dex": {
            "type": "integer"
          },
          "con": {
            "type": "integer"
          },
          "int": {
            "type": "integer"
          },
          "wit": {
            "type": "integer"
          },
          "men": {
            "type": "integer"
          }
        },
        "required": [
          "str",
          "dex",
          "con",
          "int",
          "wit",
          "men"
        ]
      },
      "stats": {
        "type": "object",
        "properties": {
          "pAtk": {
            "type": "integer"
          },
          "mAtk": {
            "type": "integer"
          },
          "pDef": {
            "type": "integer"
          },
          "mDef": {
            "type": "integer"
          },
          "accur": {
            "type": "integer"
          },
          "evasion": {
            "type": "integer"
          },
          "crit": {
            "type": "integer"
          },
          "speed": {
            "type": "integer"
          },
          "atkSpd": {
            "type": "integer"
          },
          "castSpd": {
            "type": "integer"
          }
        },
        "required": [
          "pAtk",
          "mAtk",
          "pDef",
          "mDef",
          "accur",
          "evasion",
          "crit",
          "speed",
          "atkSpd",
          "castSpd"
        ]
      },
      "vitals": {
        "type": "object",
        "properties": {
          "maxHp": {
            "type": "integer"
          },
          "maxMp": {
            "type": "integer"
          },
          "load": {
            "type": "integer"
          }
        },
        "required": [
          "maxHp",
          "maxMp",
          "load"
        ]
      },
      "speed": {
        "type": "object",
        "properties": {
          "walk": {
            "type": "integer"
          },
          "run": {
            "type": "integer"
          },
          "swim": {
            "type": "integer"
          }
        },
        "required": [
          "walk",
          "run",
          "swim"
        ]
      },
      "collision": {
        "type": "object",
        "properties": {
          "radius": {
            "type": "number"
          },
          "size": {
            "type": "number"
          }
        },
        "required": [
          "radius",
          "size"
        ]
      }
    },
    "required": [
      "template",
      "base",
      "stats",
      "vitals",
      "speed",
      "collision"
    ]
}

=== JasminDreasond/NodeL2/data/Templates/18-elven-fighter.json
{
    "template": { "baseId": 18, "classId": 18, "race": 1, "crafter": false },
    "base": { "str": 36, "dex": 35, "con": 36, "int": 23, "wit": 14, "men": 26 },
    "stats": { "pAtk": 4, "mAtk": 3, "pDef": 72, "mDef": 47, "accur": 36, "evasion": 36, "crit": 46, "speed": 126, "atkSpd": 345, "castSpd": 249 },
    "vitals": { "maxHp": 113, "maxMp": 39, "load": 73840 },
    "speed": { "walk": 90, "run": 143, "swim": 50 },
    "collision": { "radius": 7.5, "size": 24.0 }
}
