=== JasminDreasond/NodeL2/data/Items/Armors/.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "itemId": {
                "type": "integer"
            },
            "template": {
                "type": "object",
                "properties": {
                    "kind": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "mass": {
                        "type": "integer"
                    },
                    "price": {
                        "type": "integer"
                    }
                },
                "required": [
                    "kind",
                    "name",
                    "mass",
                    "price"
                ]
            },
            "stats": {
                "type": "object",
                "properties": {
                    "pDef": {
                        "type": "integer"
                    },
                    "maxMp": {
                        "type": "integer"
                    }
                },
                "required": [
                    "pDef",
                    "maxMp"
                ]
            },
            "etc": {
                "type": "object",
                "properties": {
                    "slot": {
                        "type": "integer"
                    }
                },
                "required": [
                    "slot"
                ]
            }
        },
        "required": [
            "itemId",
            "template",
            "stats",
            "etc"
        ]
    }
}

=== JasminDreasond/NodeL2/data/Items/Armors/armors.json
[{
    "itemId": 425,
    "template": { "kind": "Armor", "name": "Apprentice's Tunic", "mass": 2150, "price": 26 },
    "stats": { "pDef": 17, "maxMp": 19 },
    "etc": { "slot": 10 }
},{
    "itemId": 461,
    "template": { "kind": "Armor", "name": "Apprentice's Stockings", "mass": 1100, "price": 6 },
    "stats": { "pDef": 10, "maxMp": 10 },
    "etc": { "slot": 11 }
},{
    "itemId": 1146,
    "template": { "kind": "Armor", "name": "Squire's Shirt", "mass": 3301, "price": 26 },
    "stats": { "pDef": 33, "maxMp": 0 },
    "etc": { "slot": 10 }
},{
    "itemId": 1147,
    "template": { "kind": "Armor", "name": "Squire's Pants", "mass": 1750, "price": 6 },
    "stats": { "pDef": 20, "maxMp": 0 },
    "etc": { "slot": 11 }
}]
